### ISSUE TITLE
[Feature] 建议添加 导出文档时能生成一个包含全部接口的文档

### ISSUE THREAD

**Issue by 1107186916** [gudqs7-idea-plugins/api-savior#88]
**描述您想要的解决方案**
现在导出的文档是单个的md文件。要是能生成一个包含全部接口的md文档就更好了。

**Comment by gudqs7** [comment]
easy to do，明天下午发版

发自我的iPhone

**Comment by gudqs7** [comment]
@1107186916 可以是可以, 但这样的话, 标题目录可能需要注意处理下, 其他倒是简单, 我记得我写过导处一整个pdf, 目录利用的是pdf的目录特性做的, markdown 全靠 H1 了, 不知道效果如何. 那个版本我发布过, 见链接: https://plugins.jetbrains.com/plugin/16860-api-savior/versions/stable/210072?preview=true

**Comment by 1107186916** [comment]
![image](https://user-images.githubusercontent.com/65063196/195974869-df764838-412b-486c-9aa2-775343e88dc9.png)
![image](https://user-images.githubusercontent.com/65063196/195974908-5af26abe-bc5d-4dcb-a331-62e43e6059c8.png)

@gudqs7  用的插件2.5.3.pdf这个版本。同一份代码导出pdf文件为空。虽然都报字段转换问题的错，但是导出HTML没有问题

**Comment by gudqs7** [comment]
@1107186916 应该和这个报错无关, 可能是别的地方有问题....  pdf 就算了, 已经放弃了, 加上的话打包后的 zip 太大了, 而且意义不大, 因为 pdf 不支持 js 语法, 所以不支持高亮, 不如加上你这个 markdown, 这样用 typora 之类的软件导出pdf效果更好, 明天下午写, 晚上就能搞定

**Comment by gudqs7** [comment]
@1107186916 搞定了, 效果见我都示例项目: https://github.com/gudqs7-idea-plugins/api-savior-examples/blob/master/doc-example/restful/api-savior-examples-restful-all.md#%E7%9B%AE%E5%BD%95

目前这效果, 我尽量兼容了 GitHub 和 typora, 本来想标题后面加个 返回目录的链接, 但是发现问题很多, 好多编辑器都不支持这么写, 目前改成这样了, 也有返回目录的跳转, 在 GitHub 上效果不错

**Comment by 1107186916** [comment]
@gudqs7  无敌！非常感谢！
