### ISSUE TITLE
[Feature] 导出的字段 - 部分字段是乱码

### ISSUE THREAD

**Issue by 1107186916** [gudqs7-idea-plugins/api-savior#89]
![image](https://user-images.githubusercontent.com/65063196/195970862-e51cd108-72c3-4293-b5c8-1b9f6f5b2e59.png)

![image](https://user-images.githubusercontent.com/65063196/195970915-8427538c-dd0f-41ad-a09e-42b4a5130a34.png)

导出的文档，其中的字段是乱码。建议导出时用utf-8的格式。

**Comment by gudqs7** [comment]
@1107186916 抱歉, 这个不算乱码, 是随机中文...  不过和乱码没啥区别了... 我想办法改进下, 实在不行就写死个Hello World

**Comment by 1107186916** [comment]
@gudqs7  随机中文的话，如果没有啥好方法还是不要写死了。保持现状就行。或者可以生成字母不生成汉字

**Comment by gudqs7** [comment]
> @gudqs7 随机中文的话，如果没有啥好方法还是不要写死了。保持现状就行。或者可以生成字母不生成汉字

@1107186916  嗯, 如果有注释, 就不会生成了, 我会好好考虑下的, 光是字母不是很好, 但也是个办法.
